CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    status VARCHAR(255),
    role VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    parent_category_id BIGINT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    stock_quantity INTEGER NOT NULL,
    category VARCHAR(255),
    brand VARCHAR(255),
    image_url VARCHAR(255),
    status VARCHAR(255),
    average_rating NUMERIC(3, 2),
    review_count INTEGER NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE INDEX idx_products_status_created_at
    ON products (status, created_at);
CREATE INDEX idx_products_status_category_created_at
    ON products (status, category, created_at);
CREATE INDEX idx_products_status_brand_created_at
    ON products (status, brand, created_at);
CREATE INDEX idx_products_status_price_created_at
    ON products (status, price, created_at);
CREATE INDEX idx_products_status_stock_quantity
    ON products (status, stock_quantity);

CREATE TABLE coupons (
    coupon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    discount_type VARCHAR(255) NOT NULL,
    discount_value NUMERIC(10, 2) NOT NULL,
    min_order_amount NUMERIC(10, 2) NOT NULL,
    max_discount_amount NUMERIC(10, 2),
    valid_from TIMESTAMP(6) NOT NULL,
    valid_until TIMESTAMP(6) NOT NULL,
    issue_limit INTEGER,
    issued_count INTEGER NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_coupons_code UNIQUE (code)
);

CREATE TABLE user_coupons (
    user_coupon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    coupon_id BIGINT NOT NULL,
    status VARCHAR(255),
    issued_at TIMESTAMP(6) NOT NULL,
    used_at TIMESTAMP(6),
    order_id BIGINT,
    CONSTRAINT uk_user_coupons_user_id_coupon_id UNIQUE (user_id, coupon_id),
    CONSTRAINT fk_user_coupons_coupon_id FOREIGN KEY (coupon_id) REFERENCES coupons (coupon_id)
);

CREATE TABLE carts (
    cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_carts_user_id UNIQUE (user_id)
);

CREATE TABLE cart_items (
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_cart_items_cart_id FOREIGN KEY (cart_id) REFERENCES carts (cart_id)
);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    original_amount NUMERIC(10, 2) NOT NULL,
    discount_amount NUMERIC(10, 2) NOT NULL,
    user_coupon_id BIGINT,
    status VARCHAR(255),
    zip_code VARCHAR(255),
    address VARCHAR(255),
    detail_address VARCHAR(255),
    recipient_name VARCHAR(255),
    recipient_phone VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES orders (order_id)
);

CREATE TABLE reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    reviewer_name VARCHAR(255) NOT NULL,
    product_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    content TEXT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_reviews_user_id_product_id UNIQUE (user_id, product_id)
);

CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    method VARCHAR(255) NOT NULL,
    status VARCHAR(255),
    idempotency_key VARCHAR(100),
    pg_transaction_id VARCHAR(255),
    failure_reason VARCHAR(255),
    approved_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_payments_order_id_idempotency_key UNIQUE (order_id, idempotency_key)
);

CREATE TABLE payment_webhook_events (
    webhook_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pg_event_id VARCHAR(255) NOT NULL,
    pg_delivery_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    order_id BIGINT,
    pg_transaction_id VARCHAR(255),
    amount NUMERIC(10, 2),
    status VARCHAR(255) NOT NULL,
    failure_reason VARCHAR(255),
    pg_occurred_at TIMESTAMP(6) NOT NULL,
    received_at TIMESTAMP(6) NOT NULL,
    processed_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_payment_webhook_events_pg_event_id UNIQUE (pg_event_id)
);

CREATE TABLE payment_reconciliation_tasks (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    pg_event_id VARCHAR(255) NOT NULL,
    pg_delivery_id VARCHAR(255) NOT NULL,
    pg_transaction_id VARCHAR(255) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    pg_occurred_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_payment_reconciliation_tasks_pg_event_id UNIQUE (pg_event_id)
);

CREATE TABLE outbox_events (
    outbox_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    retry_count INTEGER NOT NULL,
    last_error TEXT,
    available_at TIMESTAMP(6) NOT NULL,
    published_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_outbox_events_event_id UNIQUE (event_id)
);

CREATE INDEX idx_outbox_events_status_available
    ON outbox_events (status, available_at, outbox_event_id);
